CREATE TABLE `transactions` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `date` datetime DEFAULT NULL,
  `title` varchar(255) NOT NULL DEFAULT '',
  `body` longtext NOT NULL,
  `pid` bigint(20) DEFAULT NULL,
  `user` varchar(255) NOT NULL DEFAULT '',
  `groupname` varchar(255) NOT NULL DEFAULT '',
  `authorized` tinyint(4) DEFAULT NULL,
  `refer_date` date DEFAULT NULL,
  `refer_from` int(11) NOT NULL DEFAULT '0',
  `refer_to` int(11) NOT NULL DEFAULT '0',
  `refer_diag` varchar(255) NOT NULL DEFAULT '',
  `refer_risk_level` varchar(255) NOT NULL DEFAULT '',
  `refer_vitals` tinyint(1) NOT NULL DEFAULT '0',
  `refer_external` tinyint(1) NOT NULL DEFAULT '0',
  `refer_related_code` varchar(255) NOT NULL DEFAULT '',
  `refer_reply_date` date DEFAULT NULL,
  `reply_date` date DEFAULT NULL,
  `reply_from` varchar(255) NOT NULL DEFAULT '',
  `reply_init_diag` varchar(255) NOT NULL DEFAULT '',
  `reply_final_diag` varchar(255) NOT NULL DEFAULT '',
  `reply_documents` varchar(255) NOT NULL DEFAULT '',
  `reply_findings` text NOT NULL,
  `reply_services` text NOT NULL,
  `reply_recommend` text NOT NULL,
  `reply_rx_refer` text NOT NULL,
  `reply_related_code` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1