<?php 
// Copyright (C) 2012 Chris Paulus <coding@cipher-naught.com>
// Sponsored by David Eschelbacher, MD
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.

$form = $this->form;
$this->form->setAction($this->url());
?>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />
<link rel="stylesheet" href="<?php echo $GLOBALS['css_header'];?>" type="text/css">
<script type="text/javascript" src="<?php echo $GLOBALS['webroot'] ?>/library/dialog.js"></script>

<link rel="stylesheet" type="text/css" href="../../../../library/js/fancybox/jquery.fancybox-1.2.6.css" media="screen" />
<script type="text/javascript" src="../../../../library/textformat.js"></script>
<script type="text/javascript" src="../../../../library/dialog.js"></script>
<script type="text/javascript" src="../../../../library/js/jquery.1.3.2.js"></script>
<script type="text/javascript" src="../../../../library/js/fancybox/jquery.fancybox-1.2.6.js"></script>

<script type="text/javascript" src="../../../../library/js/common.js"></script>

<title>Data Importer</title>
<script type="text/javascript">

function ConfirmFileDelete(btn)
{

	var r=confirm("Are you sure you want to delete this file?");
	if (r==true)
	{
		//Set hidden value.
		//document.forms[0].submit();
		//btn.value = "true";
		return true;
	}
	else {
		//btn.value = "false";
		return false;
	}
	
	
}

function ConfirmFileProcess(btn)
{

	var r=confirm("Are you sure you want to process this file?");
	if (r==true)
	{
		//Set hidden value.
		//document.forms[0].submit();
		//btn.value = "true";
		return true;
	}
	else {
		//btn.value = "Delete";
		return false;
	}
	
	
}

function SelectElement(valueToSelect,selectList)
{    
    var element = document.getElementById(selectList);
    var isFound = false;

    for (var i=0; i<element.options.length; i++)
    {
     if ( element.options[i].value == valueToSelect )
     {
    	 element.options[i].selected = true;
      isFound = true;
     }
    }
    if ( isFound == false )
    	element.options[0].selected = true;
}


function SetElement(valueToSet,ElementID)
{
	var element = document.getElementById(ElementID);
	if(valueToSet != 0)
		element.value = valueToSet;
}

</script>


<style>




hr {
  border: 0;
  width: 80%;
  height: 5px;
}


#leftContainer {
  
  width: 45%; 
  
  float:left;

  margin-left:10px;
  margin-right:10px;
  margin-top:10px;
  height: 100%;
  
}

#fileImport {
  background: #EBEBEB;
  border-style:solid;
  padding:25px 50px;
  margin-bottom:10px;
  height:40%;
  
}

#options {
  background: #EBEBEB;
  border-style:solid;
  padding:25px 50px;
  height:40%; 
}

#upperContainer {
  margin:auto;
  width: 800px; 
  border-width:10px;
  height:700px;
}
#rightContainer {
  float:right;
  width: 45%; 
  
  height:100%;
  margin-top:10px;
  margin-bottom:10px;
  margin-left:10px;
}

#tableInfo {
  
  margin:auto;
  background-color: #EBEBEB;
  border-style:solid;
  height:80%;
  width:70%;
  padding-left: 25px;
  padding-right: 25px;
  padding-top: 50px;
  padding-bottom: 62px;
}



#columnList {
  background:white;
  overflow:auto;
  height:430px;
  
}

#bottomContainer {
  
  width: 780px; 
  margin:auto;
  
  border-width:10px;
  height:600px;
  display:table;
}

#importPreview { /* this is the bottom */
  margin-top:10px;
  margin-bottom:10px;
  margin-left:40px;
  margin-right:30px;
  padding:10px 10px;
  float:left;
  width: 754px;
  height:50%;
  display:table;
  background: #EBEBEB; 
  border-style:solid;
  overflow:visible;
  
}

#buttonContainer {
	margin:auto;
	height: 50px;
	width: 800px; 
	border-width:10px;
	padding:10px 10px;
}


</style>
</head>
<body class="body_top">
<br/>
<br/>
<br/>
<br/>
<form method="<?php echo $form->getMethod() ?>" action="<?php echo $form->getAction()?>" enctype="<?php echo $form->getAttrib('enctype')?>">
	<div id="buttonContainer">
<span style="float:right;"><?php echo $form->getElement('processFile')->render(); ?></span> 

<?php echo $form->getElement('hidTableData')->render(); ?>
</div>
<div style="margin:auto;width: 800px;">Message: <?php echo $form->lblOutput; ?><br/></div>

<div id="upperContainer">
	<div id="leftContainer">
			<div id="fileImport">
			File to Import <br/>
			<?php echo $form->getElement('dataFile')->render(); ?>
			<?php echo $form->getElement('uploadFile')->render(); ?>
			<?php echo $form->getElement('fileList')->render(); ?>
			<?php echo $form->getElement('Delete')->render(); ?><?php echo $form->getElement('apply')->render(); ?>
			
			<br/>
			</div>
			<div id="options">
			Basic Options<br/>
			<table> 
			<tr>
			<td colspan="3"><a href="http://www.asciitable.com/"  target="_blank">ASCII Chart 
			 <img src="../../../../images/new_window_icon.gif" alt="Ascii Chart link"/></a></td>
			
			</a></td>
			</tr>
			<tr>
			<td>Field Delimiters </td>
			<td valign="bottom">
			
			
			<?php echo $form->getElement('fieldDelimit')->render(); ?> 
			
			
			</td>
			<td valign="bottom"><?php echo $form->getElement('fieldDelimitBox')->render(); ?>
    	
    	
    	<br/></td>
			</tr>
			<tr>
			<td colspan="3" align="right"><?php echo $form->getElement('dateSelect')->render(); ?></td>
			
			</tr>	
			<tr>
			
			<td>
			Text Qualifier </td><td><?php echo $form->getElement('txtQualifier')->render(); ?></td>
			<td><?php echo $form->getElement('txtQualifierBox')->render(); ?></td>
			</tr>
			</table>
			<hr/>
			Advanced Options<br/>
			<table>
			<tr>
				<td>Text Encoding</td>
				<td><?php echo $form->getElement('txtEncoding')->render(); ?></td>
				
			</tr>
			<tr>
			<td>First Row is Column Headings?</td>
			<td><?php echo $form->getElement('firstRowColumnHeading')->render(); ?></td>
			</tr>
			</table>
			 
			
			
			</div>
		</div>
		<div id="rightContainer">
			<div id="tableInfo">
			Table Info<br/>
			<?php 
			
			echo $form->getElement('tableList')->render(); 
			?>
			
			
			<br/>
			List of Columns:
			<div id="columnList" >
			
<?php 
	echo $this->ArrayView()->makeAlternatingDiv($form->columnListSet,"gray");
	
?>
			
			
			
			</div>
		</div>
</div>
<div id="spacer">
</div>
</div>
</div>

<br/>

<hr class="middleBar"/>
<div id="bottomContainer">
	<div id="importPreview">
	Import Previews<br/>
	Number of Rows to Preview: <?php echo $form->getElement('rowLimitList')->render(); ?>
	 <br/>
	<?php 
	
	if($form->previewTableStatus == "render") {
		//Add skip, send in select list
		//generateTable($tableData, $listOfColumns, $columnChoice = null)
		$lclTest = $form->previewTableData[0];
		echo $this->TableViewHelper()->generateTable($form->previewTableData[0],
                                                     
                                               $form->columnListSet,
                                               $form->previewTableData[1]
                                       );
	}
	else {
		echo $form->previewTableStatusMessage;
	}
			
	//echo $form->previewTable; 
	
	?>
	
	</div>
<br/>

<?php
//echo $this->dataBaseTables()->tableList();
?>
</div>
</form>

</body>
</html>