<?php 

$form = $this->form;
$this->form->setAction($this->url());
?>

<html>
<body>
<br /><br />
<div id="view-content">

<form method="<?php echo $form->getMethod() ?>" action="<?php echo $form->getAction() ?>" >
	<p>You are about to upload data.  Click procced to continue or cancel to end.</p>
	
	<?php echo $form->pageMessage; ?>
	<br/>
	<?php echo $form->getElement('proceed')->render(); ?>
	<br/>
	<?php echo $form->getElement('cancel')->render(); ?>
	
	<br/>
</form>
	</div>
</body>
</html>